"use client";

import { memo, useState, useCallback } from 'react';
import { Handle, Position, NodeProps } from 'reactflow';
import { Link2, Plus, Trash2, Edit3, Check, X, ArrowRightLeft, Database, Link } from 'lucide-react';
import { cn } from '@/lib/utils';
import { useDiagramStore } from '@/store/use-diagram-store';
import { Column, TableNodeData } from './table-node';

export type JunctionTableNodeData = {
    label: string;
    columns: Column[];
    sourceTable: string;
    targetTable: string;
    sourceColumn: string;
    targetColumn: string;
    isAutoGenerated?: boolean;
};

const JunctionTableNode = ({ data, selected, id }: NodeProps<JunctionTableNodeData>) => {
    const [editingTable, setEditingTable] = useState(false);
    const [tableName, setTableName] = useState(data.label);

    const { renameTable, deleteTable } = useDiagramStore();

    const handleTableRename = useCallback(() => {
        if (tableName.trim() && tableName !== data.label) {
            renameTable(id, tableName.trim());
        }
        setEditingTable(false);
    }, [tableName, data.label, id, renameTable]);

    const handleDeleteTable = useCallback(() => {
        deleteTable(id);
    }, [id, deleteTable]);

    return (
        <>
            <div
                className={cn(
                    "bg-gradient-to-br from-purple-50 to-blue-50 dark:from-purple-900/20 dark:to-blue-900/20 border-2 border-purple-300 dark:border-purple-700 rounded-lg shadow-lg min-w-[220px] transition-all",
                    selected ? "border-purple-500 ring-2 ring-purple-500 shadow-xl scale-[1.02]" : "",
                    data.isAutoGenerated && "opacity-90"
                )}
            >
                {/* Table Header with Junction Indicator */}
                <div className="bg-gradient-to-r from-purple-600 to-blue-600 text-white p-3 rounded-t-lg">
                    <div className="flex items-center justify-between">
                        <div className="flex items-center gap-2">
                            <ArrowRightLeft className="w-4 h-4" />
                            <Database className="w-4 h-4" />
                            {editingTable ? (
                                <div className="flex items-center gap-1 flex-1">
                                    <input
                                        type="text"
                                        value={tableName}
                                        onChange={(e) => setTableName(e.target.value)}
                                        onKeyDown={(e) => e.key === 'Enter' && handleTableRename()}
                                        className="bg-white/20 border border-white/30 rounded px-2 py-1 text-sm flex-1 text-white placeholder-white/70"
                                        autoFocus
                                    />
                                    <button onClick={handleTableRename} className="text-white hover:text-green-200">
                                        <Check className="w-3 h-3" />
                                    </button>
                                    <button onClick={() => setEditingTable(false)} className="text-white hover:text-red-200">
                                        <X className="w-3 h-3" />
                                    </button>
                                </div>
                            ) : (
                                <span className="font-bold text-sm">{data.label}</span>
                            )}
                        </div>
                        <div className="flex gap-1">
                            {!editingTable && (
                                <>
                                    <button
                                        onClick={() => setEditingTable(true)}
                                        className="text-white/80 hover:text-white p-0.5"
                                    >
                                        <Edit3 className="w-3 h-3" />
                                    </button>
                                    <button
                                        onClick={handleDeleteTable}
                                        className="text-white/80 hover:text-red-200 p-0.5"
                                    >
                                        <Trash2 className="w-3 h-3" />
                                    </button>
                                </>
                            )}
                        </div>
                    </div>
                    {data.isAutoGenerated && (
                        <div className="text-xs text-white/80 mt-1 italic">
                            Auto-generated junction table
                        </div>
                    )}
                </div>

                {/* Junction Info */}
                <div className="p-3 border-b border-purple-200 dark:border-purple-800">
                    <div className="text-xs space-y-1">
                        <div className="flex items-center justify-between">
                            <span className="font-medium text-purple-700 dark:text-purple-300">Connects:</span>
                        </div>
                        <div className="flex items-center gap-2 text-muted-foreground">
                            <div className="bg-purple-100 dark:bg-purple-900/30 px-2 py-1 rounded text-xs font-mono">
                                {data.sourceTable}
                            </div>
                            <Link2 className="w-3 h-3 text-purple-500" />
                            <div className="bg-blue-100 dark:bg-blue-900/30 px-2 py-1 rounded text-xs font-mono">
                                {data.targetTable}
                            </div>
                        </div>
                    </div>
                </div>

                {/* Columns */}
                <div className="p-3 space-y-2">
                    <div className="text-xs font-medium text-purple-700 dark:text-purple-300 mb-2">
                        Foreign Keys:
                    </div>
                    {data.columns.map((col) => (
                        <div key={col.id} className="flex items-center gap-2 text-xs p-2 bg-white/50 dark:bg-black/20 rounded border border-purple-200 dark:border-purple-800">
                            <Link className="w-3 h-3 text-blue-500 shrink-0" />
                            <span className="font-mono text-foreground/90">{col.name}</span>
                            <span className="text-[10px] uppercase opacity-70 text-muted-foreground">{col.type}</span>
                            {col.isNullable && <span className="text-[9px] border border-border px-1 rounded text-muted-foreground/70">NULL</span>}
                        </div>
                    ))}

                    {data.columns.length === 0 && (
                        <div className="text-xs text-muted-foreground text-center italic py-2">
                            No foreign key columns
                        </div>
                    )}
                </div>

                {/* Footer */}
                <div className="bg-purple-100/50 dark:bg-purple-900/20 px-3 py-2 rounded-b-lg border-t border-purple-200 dark:border-purple-800">
                    <div className="text-xs text-purple-700 dark:text-purple-300 flex items-center gap-1">
                        <ArrowRightLeft className="w-3 h-3" />
                        Many-to-Many Relationship
                    </div>
                </div>

                <Handle
                    type="target"
                    position={Position.Left}
                    className="!bg-purple-500 !border-background !w-3 !h-3"
                />
                <Handle
                    type="source"
                    position={Position.Right}
                    className="!bg-purple-500 !border-background !w-3 !h-3"
                />
                <Handle
                    type="target"
                    position={Position.Top}
                    className="!bg-blue-500 !border-background !w-3 !h-3"
                />
                <Handle
                    type="source"
                    position={Position.Bottom}
                    className="!bg-blue-500 !border-background !w-3 !h-3"
                />
            </div>
        </>
    );
};

export default memo(JunctionTableNode);
